spring:
  session:
    store-type: ${type:redis}
    redis:
      namespace: ${namespace:test}
      configure-action: none # disable destroy event processing to optimize performance
      cleanup-cron: '-' # disable run of clean up job (to prevent unnecessary requests to redis)
    timeout: ${timeout:60}
  redis:
    host: localhost
    port: 6379
  security:
    user:
      name: user
      password: pass

logging:
  level:
    org.springframework.security: DEBUG