spring:
  session:
    store-type: ${type:redis}
    redis:
      namespace: ${namespace:test}
    timeout: ${timeout:60}
  redis:
    host: localhost
    port: 6379
  security:
    user:
      name: user
      password: pass

logging:
  level:
    org.springframework.security: DEBUG